// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorTemplatesLawler.Models;

namespace RazorTemplatesLawler.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20210222024938_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorTemplatesLawler.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Lukas",
                            Grade = "A-",
                            LastName = "Lawler"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "David",
                            Grade = "C",
                            LastName = "Davison"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Al",
                            Grade = "D+",
                            LastName = "Bundy"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Ed",
                            Grade = "F",
                            LastName = "Eddneddy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
